### ISSUE TITLE
Encountered Syntax error while running this code script

### ISSUE THREAD

**Issue by babaralishah** [astronomer/dynamic-dags-tutorial#2]
This is the syntax error that i am having after executing this code...

Broken DAG: [/opt/airflow/dags/Dags Dynamic/include/dag-template.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dags Dynamic/include/dag-template.py", line 9, in <module>
    dag = DAG(dag_id,
NameError: name 'dag_id' is not defined

![image](https://user-images.githubusercontent.com/37935603/152154465-b16bb3c8-860f-4915-be56-86afd0f9c533.png)

**Comment by pedro14ha** [comment]
Hello @babaralishah You need to upload just the **dags/** folder of project inside the **dags/** folder of Airflow. As you can see here [/opt/airflow/dags/Dags Dynamic/include/dag-template.py], all the project is inside de **dags/** folder. The error in the file dag-template.py is because it is just a template, and do not stay in **dags/** folder,  just in **include/** folder.
